=== BernatJulioVerne/LM/UD5_XML/ejemplos/dtd/instituto/instituto.dtd
<!ELEMENT consejeria (instituto*)>
<!ELEMENT instituto (personas,modulos)>
<!ATTLIST instituto nombre CDATA #REQUIRED>
<!ATTLIST instituto direccion CDATA #REQUIRED>
<!ENTITY cifconsejeria "c-12345678-a">
<!ATTLIST instituto cif CDATA #REQUIRED>
<!ELEMENT personas (persona*)>
<!ELEMENT persona (nombre,apellidos,edad)>
<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST persona rol (alumnado|docente) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT modulos (modulo*)>
<!ELEMENT modulo (nombremodulo,matriculados,horassemana)>
<!ATTLIST modulo id ID #REQUIRED>
<!ATTLIST modulo docente IDREF #REQUIRED>
<!ATTLIST modulo ciclo NMTOKEN #REQUIRED>
<!ELEMENT nombremodulo (#PCDATA)>
<!ELEMENT horassemana (#PCDATA)>
<!ELEMENT matriculados (matriculado+)>
<!ELEMENT matriculado EMPTY>
<!ATTLIST matriculado idPersona IDREF #REQUIRED>

=== BernatJulioVerne/LM/UD5_XML/ejemplos/dtd/instituto/instituto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE consejeria SYSTEM "instituto.dtd">
<consejeria>
    <instituto nombre="adfsafsd" direccion="assdfdf" cif="%cifconsejeria">

       <modulos>
        <modulo id="1" docente="p2" ciclo="DAM">
            <nombremodulo>Acceso a Datos</nombremodulo>
            <matriculados>
                <matriculado idPersona="p1" />
                <matriculado idPersona="p3" />
            </matriculados>
            <horassemana>6</horassemana>
        </modulo>
        <modulo id="2" docente="p4" > 
            <nombremodulo>Programacion</nombremodulo>
            <matriculados>
            </matriculados>
            <horassemana>6</horassemana>
        </modulo>
    </modulos>
    <personas>
        <persona id="p1" rol="alumnado">
            <nombre>Maria</nombre>
            <apellidos>Sanchez</apellidos>
           <edad>21</edad>
        </persona>
        <persona id="p2" rol="docente">
            <nombre>Jose</nombre>
            <apellidos>Garcia</apellidos>
            <edad>35</edad>
        </persona>
        <persona id="p3" rol="alumnado">
            <nombre>Antonio</nombre>
            <apellidos>Jimenez</apellidos>
            <edad>20</edad>
        </persona>
        <persona id="p4" rol="director">
            <nombre>Manuel</nombre>
            <apellidos>Jimenez</apellidos>
            <edad>40</edad>
        </persona>
    </personas>
    </instituto>
</consejeria>

=== BernatJulioVerne/LM/UD5_XML/ejemplos/dtd/instituto/instituto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE consejeria SYSTEM "instituto.dtd">
<consejeria>
    <instituto nombre="adfsafsd" direccion="assdfdf" cif="&cifconsejeria;">
       <personas>
            <persona id="p1" rol="alumnado">
                <nombre>Maria</nombre>
                <apellidos>Sanchez</apellidos>
               <edad>21</edad>
            </persona>
            <persona id="p2" rol="docente">
                <nombre>Jose</nombre>
                <apellidos><![CDATA[ c&a< >  " ']]></apellidos>
                <edad>35</edad>
            </persona>
            <persona id="p3" rol="alumnado">
                <nombre>Antonio</nombre>
                <apellidos>Jimenez</apellidos>
                <edad>20</edad>
            </persona>
        </personas>
       <modulos>
        <modulo id="m1" docente="p2" ciclo="DAM">
            <nombremodulo>Acceso a Datos</nombremodulo>
          
            <matriculados>
                <matriculado idPersona="p1" />
                <matriculado idPersona="p3" />
            </matriculados>
            <horassemana>6</horassemana>
            <url>
                <![CDATA[ 
                https://dfgdsf.es/index.html?sdfsdf=sfdf&fg=sdfs
                ]]>
            </url>
            </modulo>
    </modulos>
    </instituto>
</consejeria>
