=== BernatJulioVerne/LM/UD5_XML/ejemplos/dtd/rebelion/rebelion.dtd
<!-- rebelion.dtd -->
<!ELEMENT rebelion (planetas,personas,naves)>
<!ELEMENT planetas (planeta+)>
<!ELEMENT planeta (nombrePlaneta,tipo)>
<!ATTLIST planeta id ID #REQUIRED>
<!ELEMENT nombrePlaneta (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,edad,origen)>
<!ATTLIST persona id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ATTLIST origen id IDREF #REQUIRED>
<!ELEMENT naves (nave+)>
<!ELEMENT nave (matricula,modelo)>
<!ATTLIST nave id ID #REQUIRED>
<!ATTLIST nave comandante IDREF #REQUIRED>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>

=== BernatJulioVerne/LM/UD5_XML/ejemplos/dtd/rebelion/rebelion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rebelion SYSTEM "rebelion.dtd">
<rebelion>

    <planetas>
        <planeta id="p1">
            <nombrePlaneta>Tatooine</nombrePlaneta>
            <tipo>Des√©rtico</tipo>
        </planeta>
        <planeta id="p2">
            <nombrePlaneta>Alderaan</nombrePlaneta>
            <tipo>Terrestre</tipo>
        </planeta>
        <planeta id="p3">
            <nombrePlaneta>Corellia</nombrePlaneta>
            <tipo>Boscoso</tipo>
        </planeta>
    </planetas>
    <personas>
        <persona id="m1">
            <nombre>Luke Skywalker</nombre>
            <edad>25</edad>
            <origen id="p1" />
        </persona>
        <persona id="m2">
            <nombre>Leia Organa</nombre>
            <edad>25</edad>
            <origen id="p2" />
        </persona>
        <persona id="m3">
            <nombre>Han Solo</nombre>
            <edad>30</edad>
            <origen id="p1" />
        </persona>
    </personas>
    <naves>
        <nave id="n1" comandante="p1">
            <matricula>1234qwe</matricula>
            <modelo>X-wing</modelo>
        </nave>
        <nave id="n2" comandante="m2">
            <matricula>9876asd</matricula>
            <modelo>Y-wing</modelo>
        </nave>
        <nave id="n3" comandante="m3">
            <matricula>1234qwe</matricula>
            <modelo>Millenium Falcon</modelo>
        </nave>
    </naves>
</rebelion>
